name: 'Compile'

on:
  push:
    tags:
      - '*'

jobs:
  Skip_Checking:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5

  Compile:
    needs: Skip_Checking
    if: needs.Skip_Checking.outputs.should_skip != 'true'
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        versions: [6.6.1, 6.5.3, 6.2.7]
    
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qt-builder
            ${{ vars.REGISTRY }}/qt-builder
          tags: ${{ matrix.versions }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Github Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USER_GITHUB_PERSONAL }}
          password: ${{ secrets.TOKEN_GITHUB_PERSONAL }}

      - name: Set QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Load
        id: build3x
        uses: docker/build-push-action@v4
        with:
          context: ./BuilderQt
          platforms: linux/amd64,linux/arm64
          target: artifact
          output: type=local,dest={{ github.workspace }}/build
          build-args: VERSION=${{ matrix.versions }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/linux_amd64/Qt-amd64.tar.xz
            build/linux_arm64/Qt-arm64.tar.xz

      - name: Cleanup Folders
        run: rm -r ${{ github.workspace }}/build*