name: 'Build'

on:
  push:
    branches:
      - "*"
      - "!main"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  VERSION: 6.6.1

jobs:
  Build QtBuilder:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/qt-builder
          ${{ vars.REGISTRY }}/qt-builder
        tags: type=raw,value=6
        flavor: onlatest=false

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to Github Container Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.USER_GITHUB_PERSONAL }}
        password: ${{ secrets.TOKEN_GITHUB_PERSONAL }}

    - name: Set QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Upload Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./QtBuilder
        platforms: linux/amd64
        file: ${{ github.workspace }}/QtBuilder/Dockerfile.builder
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  Build Qt:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        version: [${{ env.VERSION }}]

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Build AMD64
      run: |
        docker run --rm -v ${{ github.workspace }}/build:/root/export ${{ vars.REGISTRY }}/qt-builder:6 /build_qt6_amd64.sh ${{ matrix.version }}

    - name: Build ARM64
      run: |
        docker run --rm -v ${{ github.workspace }}/build:/root/export ${{ vars.REGISTRY }}/qt-builder:6 /build_qt6_arm64.sh ${{ matrix.version }}

    - name: Upload Qt AMD64 Library
      uses: actions/upload-artifact@v2
      with:
        name: Qt-amd64-${{ matrix.version }}.tar.xz
        path: ${{ github.workspace }}/build/Qt-amd64-${{ matrix.version }}.tar.xz

    - name: Upload Qt ARM64 Library
      uses: actions/upload-artifact@v2
      with:
        name: Qt-arm64-${{ matrix.version }}.tar.xz
        path: ${{ github.workspace }}/build/Qt-arm64-${{ matrix.version }}.tar.xz


  Build Qt Developmnet Image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        version: [${{ env.VERSION }}]

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Download Qt AMD64 Library
      uses: actions/download-artifact@v2
      with:
        name: Qt-amd64-${{ matrix.version }}.tar.xz
        path: ${{ github.workspace }}/build/Qt-amd64-${{ matrix.version }}.tar.xz

    - name: Download Qt ARM64 Library
      uses: actions/download-artifact@v2
      with:
        name: Qt-arm64-${{ matrix.version }}.tar.xz
        path: ${{ github.workspace }}/build/Qt-arm64-${{ matrix.version }}.tar.xz

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/qt-dev-base
          ${{ vars.REGISTRY }}/qt-dev-base
        tags: type=raw,value=${{ matrix.version }}
        flavor: onlatest=false

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to Github Container Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.USER_GITHUB_PERSONAL }}
        password: ${{ secrets.TOKEN_GITHUB_PERSONAL }}

    - name: Build Development Image
      uses: docker/build-push-action@v4
      with:
        context: ./QtDev
        platforms: linux/amd64,linux/arm64
        file: ${{ github.workspace }}/QtDev/Dockerfile.dev
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: QTVER=${{ matrix.version }}